# Assignment_10.2
In this assignment, students will be using the K-nearest neighbors algorithm to predict
how many points NBA players scored in the 2013-2014 season.
A look at the data
Before we dive into the algorithm, letâ€TMs take a look at our data. Each row in the data
contains information on how a player performed in the 2013-2014 NBA season.
Download 'nba_2013.csv' file from this link:
https://www.dropbox.com/s/b3nv38jjo5dxcl6/nba_2013.csv?dl=0
Here are some selected columns from the data:
player - name of the player
pos - the position of the player
g - number of games the player was in
gs - number of games the player started
pts - total points the player scored
There are many more columns in the data, mostly containing information about average
player game performance over the course of the season. See this site for an explanation
of the rest of them.
We can read our dataset in and figure out which columns are present:

import pandas
with open("nba_2013.csv", 'r') as csvfile:
nba = pandas.read_csv(csvfile)

In [1]:
import numpy as np
import pandas as pd

dataset = pd.read_csv('nba_2013.csv')

#removing unwanted columns from the data set
dataset.pop('player')#,'bref_team_id','season','seasom_end')
dataset.pop('bref_team_id')
dataset.pop('season')
dataset.pop('season_end')

#Categorise the data 
dataset['pos']= pd.Categorical(dataset['pos']).codes

#Handling missing data
from sklearn.preprocessing import Imputer
imp = Imputer(missing_values='NaN', strategy = 'mean', axis =1)
dataset = imp.fit_transform(dataset)

#forming X and y co-ordinates 
X = dataset[:,:-1]
y = dataset[:,-1]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.2, random_state = 0)

#implementing the above sets to KNN model
from sklearn.neighbors import KNeighborsRegressor

for k in range(25):
    k += 1
    knn = KNeighborsRegressor(n_neighbors=k, weights='uniform', algorithm='auto')
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)

In [3]:
print("values for which we need to predict the points: ", X_test)
print("predicted values for X_test are:", y_pred)

values for which we need to predict the points:  [[  3.  25.  22. ...   7.  20.  47.]
 [  3.  31.  79. ...  32. 121. 140.]
 [  3.  24.  80. ...  69. 135. 193.]
 ...
 [  5.  22.  78. ...  20.  76. 114.]
 [  3.  33.  34. ...   0.  34.  72.]
 [  4.  27.  30. ...   2.  99.  65.]]
predicted values for X_test are: [ 330.36  735.96 1033.92    6.04  920.28  341.8   333.36  659.8    78.
   22.4  1054.24   39.12   94.72   30.32  438.8  1598.4   114.12    6.04
 1229.68   95.48  221.96   84.96 1037.64 1107.28  640.88  103.24    6.04
  918.12 1221.36  781.36  180.08  436.8   555.16  339.76 1056.44 1520.64
  333.96    6.04   18.2    25.28  707.2   407.04  666.68   15.88    6.04
  326.68  414.76   70.8   115.64   57.24  191.56  601.04   48.08  969.36
  807.28   33.52  351.64    6.04  425.76  169.24    6.04  445.48  688.64
  361.92  207.4   837.04  560.88   36.36  452.84  161.64  976.12   10.92
   27.64   37.76  329.08   84.    383.12  205.72  682.64  857.88  639.04
  992.12  555.   1420.32    6.04  3